id: PD7FD3E31
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: bo
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    85b93d0c10124c8a87c3b73aff8953d8:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    6535cbea53954db4b329c66efeea9729:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    5cf1f0c9ebcf4878b6b35794727d1530:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    50a7f3f464c947a7a85024c8ef5a15f3:
      title: Praise to Mañjughoṣa
      parent: Praise
    bd95ea9aa3f44433995df4912faf70a2:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    96741a39af7c4bd29ad728253f58e59a:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    41d4c95cbe594f28acb867f286f2a0db:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    11be94ff5699472c96bdaa5413ef37bb:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.976080'
last_modified_at: '2022-03-01T01:55:51.976082'
